version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped
volumes:
  neo4j_data:
  neo4j_logs:
