version: '3.8'
services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle_db
    environment:
      - ORACLE_PWD=oraclepassword
      - ORACLE_SID=ORCL
    ports:
      - "1521:1521"  # SQL*Net
      - "5500:5500"  # Enterprise Manager
    volumes:
      - oracle_data:/opt/oracle/oradata
    shm_size: 8g
    restart: unless-stopped
volumes:
  oracle_data:
