version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_db
    command: redis-server --requirepass mypassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data:
